### ISSUE TITLE
Ollama missing support for tool calling stream (underlying langchain issue)

### ISSUE THREAD

**Issue by Teeeeg** [JoshuaC215/agent-service-toolkit#105]
I checked the   
`  
    async for event in agent.astream_events(**kwargs, version="v2"):  
        if not event:  
            continue 
`

If there is a ToolNode, there is not onToolStart kind of event. Causing no further updates on the response.
I am not sure it is a bug with LangGraph.

<img width="727" alt="image" src="https://github.com/user-attachments/assets/e0330533-21ca-4346-af94-497fe20a154d">

**Comment by JoshuaC215** [comment]
Hi @Teeeeg can you provide some more details or a full repro on what you did? What code did you modify, or how were you running the project?

From your message, it isn't really clear and I'm not able to repro it.

**Comment by Teeeeg** [comment]
> Hi @Teeeeg can you provide some more details or a full repro on what you did? What code did you modify, or how were you running the project?
> 
> From your message, it isn't really clear and I'm not able to repro it.

Hi, I did some research. This issue is caused by Ollama tool calling, it doesn’t have an ontoolstart event.
Official Langraph has the same issue!

Maybe we can work out other ways to make Ollama support streaming.


FYI:
Only codes to integrate Ollama(ChatOpenAI client url change only)
I tested it with gpt-4o and Ollama llama3.1.
The invoke API works fine, but the stream API doesn’t output all the nodes, it seems end in tool node.

I am thinking using other API instead of agent.astream_events(**kwargs, version="v2")

**Comment by JoshuaC215** [comment]
Nice! I would recommend to work on the LangChain Ollama implementation to add ontoolstart

I don't think we'll take any major refactors in the main repo to add this support although if there's a quick simple fix it would be welcome. The `agent.astream_events` is pretty key so I doubt this will change.

If there's a more complex fix you find that we can describe for other users or make available in a fork, that would be welcome. If there's more demand for this use case we can see.

**Comment by Teeeeg** [comment]
Will investigate in Ollama

**Comment by madtank** [comment]
I've had a local branch using ollama, the only issue is with streaming response.

**Comment by Teeeeg** [comment]
> I've had a local branch using ollama, the only issue is with streaming response.

Yes, the Ollama streaming is not working

**Comment by Teeeeg** [comment]
Good news. Ollama has supported ToolNode Streaming !
