### ISSUE TITLE
problem with connection to database

### ISSUE THREAD

**Issue by Dominik-Majcherczyk** [JoshuaC215/agent-service-toolkit#113]
Hi! I created a minimalist tool that is supposed to connect to my local database (maria db, localhost). The database works - I am able to connect to it from a test file. Unfortunately, inside the application, the tool is unable to find the specific database. Does anyone know what could be the problem? Could it possibly be due to the docker?

![image](https://github.com/user-attachments/assets/43454f75-6019-408b-a94f-129d6cbbfeef)

minimalist tool:

```
def list_tables_func(query: str = "") -> str:
    """Lists all tables in the connected MariaDB database.
    
    Useful for when you need to know what tables are available in the database.
    Returns a simple list of table names.
    
    Args:
        query (str): Ignored, kept for compatibility with tool interface.
        
    Returns:
        str: Newline-separated list of table names.
    """
    try:
        connection = mysql.connector.connect(
        host="172.17.0.1",
        port=3306,
        user="root",
        password="root"
    )
        
        cursor = connection.cursor()
        cursor.execute("SHOW TABLES")
        tables = cursor.fetchall()
        
        return "\n".join(table[0] for table in tables)
        
    except Exception as e:
        raise ValueError(
            f"list_tables() raised error: {e}."
            " Please check database connection and credentials"
        )
        
    finally:
        if 'cursor' in locals():
            cursor.close()
        if 'connection' in locals() and connection.is_connected():
            connection.close()
```

**Comment by Dominik-Majcherczyk** [comment]
test file which is working perfectly fine:

`import mysql.connector

def test_db_connection():
    try:
        connection = mysql.connector.connect(
            host="172.17.0.1",
            port=3306,
            user="root",
            password="root"
        )
        
        if connection.is_connected():
            print("Successfully connected to the database!")
            
            # Test querying tables
            cursor = connection.cursor()
            cursor.execute("SHOW TABLES")
            tables = cursor.fetchall()
            
            print("\nTables in database:")
            for table in tables:
                print(f"- {table[0]}")
                
    except Exception as e:
        print(f"Error: {e}")
        
    finally:
        if 'cursor' in locals():
            cursor.close()
        if 'connection' in locals() and connection.is_connected():
            connection.close()
            print("\nDatabase connection closed.")

if __name__ == "__main__":
    test_db_connection()`

**Comment by JoshuaC215** [comment]
Yes, if you're running the service in docker and running the test file directly in local python, then the docker networking is probably the issue.

You could validate that by running the service in local python too. See the [instructions here](https://github.com/JoshuaC215/agent-service-toolkit/blob/main/README.md#local-development-without-docker).
