### ISSUE TITLE
Upgrade to LangGraph v0.2 Compatibility

### ISSUE THREAD

**Issue by jabra** [JoshuaC215/agent-service-toolkit#2]
After downloading the latest version of [LangGraph Studio (Beta)](https://github.com/langchain-ai/langgraph-studio) today, I noticed that it only supports the newly released [LangGraph v0.2](https://blog.langchain.dev/langgraph-v0-2/). The LangGraph v0.2 update introduces breaking changes, particularly when loading the agent folder in LangGraph Studio. To maintain compatibility, an upgrade to the new structure should be implemented.

<img width="673" alt="image" src="https://github.com/user-attachments/assets/a52b9ef0-9594-4183-9343-0147151b5665">

**Comment by jabra** [comment]
@JoshuaC215 I made the changes for myself and I'm happy to push my changes if you allow me to push a branch -> PR.

**Comment by JoshuaC215** [comment]
Thanks for reporting @jabra !

I wanted to test locally until I can get some more robust CI so was easy for me to just make the fix. LMK if the merged fix works for you or still causes issues (or any other suggestions / PRs on how to improve)

For future reference, are you able to open a PR by forking the repo and opening from your own branch there? I'd prefer that workflow vs opening permissions to push here (at least for now).

**Comment by jabra** [comment]
All good, want to help since i want to make it work for me.
I just discovered that feature of creating PR from a forked repo, super awesome.
