### ISSUE TITLE
Token-level streaming with Gemini

### ISSUE THREAD

**Issue by peterkeppert** [JoshuaC215/agent-service-toolkit#30]
I was testing the toolkit and discovered that while token-level streaming was working great with OpenAI models, it wasn't working properly with Gemini (running on VertexAI) and I was getting only the final message from the model. For some reason, _on_llm_new_token()_ in _TokenQueueStreamingHandler_ was never called and I didn't find a reason why. I doubt the issue was with my setup, as I just switched the models in _research_assistant.py_ and double-checked _streaming=True_ is present. I am using Langchain 0.2.15.

I was able to fix the issue and have token-level stremaing working consistently for both models by switching from _.astream()_ to _.astream_events()_ ([docs](https://langchain-ai.github.io/langgraph/concepts/low_level/#astream_events-for-streaming-tokens-of-llm-calls)) in _message_generator()_ and catching _on_chain_end_/_ChannelWrite_ events for messages updating the state and _on_chat_model_stream_ events for token stream. However this is quite a conceptual change for a relatively small issue (not to mention that event streaming API is still in Beta).

Did anybody have the same issue with Gemini and perhaps found a better way to fix it?

**Comment by saltwicks** [comment]
I'm experiencing the same issue with a custom langchain ChatModel. Would you be able to share the fix you implemented by changing over to astream_events and modifying the callback?

**Comment by JoshuaC215** [comment]
Yeah feel free to post a PR even in draft, might be a useful reference for others. I won’t be able to take a close look before next week. I haven’t gotten the current approach working other than with OpenAI. I’d be curious how it works with other OpenAI-compatible APIs (like FastChat) but not at all opposed to a different approach if it provides better coverage of model providers. Thank you!

**Comment by peterkeppert** [comment]
I have attached a draft PR. For the moment I didn't find a better way to select relevant _on_chain_end_ events. I guess it might get more straightforward as event streaming API evolves. Also, it is tested only on a simple graph from within the toolkit, I will have an opportunity to check it on a more complex example hopefully next week.

**Comment by JoshuaC215** [comment]
BTW, it's probably a separate PR but if you have simple code for running this with a Gemini model would love to include that in the base repo as well!

**Comment by JoshuaC215** [comment]
Resolved with #32 thank you again for opening this and getting the fix started!

If you have a simple way to add Gemini as an example and want to create another PR please do
