### ISSUE TITLE
Streamlit app is ending with no error

### ISSUE THREAD

**Issue by ramkipalle** [JoshuaC215/agent-service-toolkit#31]
When I run the streamlit app, it is abruptly ending at the following line in the handle_feedback() function.

feedback = st.feedback("stars", key=latest_run_id)

Any idea?

**Comment by JoshuaC215** [comment]
Hey, it might be because you're using an older Streamlit version? Since st.feedback was just added in the last few versions. What error message are you getting? Try running on Streamlit 1.37+ and see if you still get the same error.

**Comment by JoshuaC215** [comment]
Going to close until there's a clearer repro description and details
