### ISSUE TITLE
Cleaning up ChatMessage ?

### ISSUE THREAD

**Issue by JoshuaC215** [JoshuaC215/agent-service-toolkit#49]
We were having some [debate](https://github.com/JoshuaC215/agent-service-toolkit/pull/42#issuecomment-2395542834) about whether / how to clean up the ChatMessage class in `schema/` which is a thin wrapper around LangChain BaseMessage, which is starting to add more complexity than value.

A few options:
1. Do nothing, keep ChatMessage. Maybe it's a useful abstraction. However it adds a lot of complexity with the BackgroundTask idea built out in !42
2. Remove ChatMessage, just return LangChain BaseMessages. Pass on any complexity like the Anthropic format to the consumer
3. Use the BaseMessage but make a best effort to clean up and always return the "simple" type, specifically having content=str or empty str if there's a tool use in an AIMessage. This would be similar to the behavior of ChatMessage today (in fact the JSON version might end up equivalent or very close)

If we go with 2 or 3 there are a couple of other considerations:
- Dealing with `run_id` - This is added to ChatMessage today and needs to also be added to a new baseMessage. Maybe in additional_kwargs?
- Best way to serialize LC BaseMessage - LC provides a `message_to_dict` / `messages_from_dict` functions which are used a bit in `schema.py` today. However the serialization format is kind of ugly. Maybe we can just use `.model_dump()`?

Without trying to implement it, I'd be in favor of (3) to maintain a similar pattern to today but simplify the schema and extra abstractions in this template. Also welcome thoughts and other ideas from users!

**Comment by JoshuaC215** [comment]
cc @peterkeppert @antonioalegria @gbaian10 @3x10RaiseTo8 what do you think?

**Comment by antonioalegria** [comment]
I tend to prefer (1) because encapsulating all of that complexity in a single place makes the client and presentation layer much simpler and easier to **adapt**.

Having said that, there's probably the need to support richer kinds of outputs and tasks. To me that suggests an expansion of the ChatMessage to have a list of Tasks and perhaps an extensible support for "rich content" -- i.e. not just text. In this case you wouldn't need to support it here but leave the extension point for the implementer.

Regarding (3), note that there are AIMessages with tool calls and a message.

**Comment by gbaian10** [comment]
I also prefer option 1, but I hope to change the `original` to retain only the `response_metadata` part (which model was used and how many tokens were spent). The other content seems almost entirely repetitive.

Additionally, the current API only returns the last message, and the type always appears to be "ai".
![image](https://github.com/user-attachments/assets/d95313d5-41eb-42a3-af36-2eeafe706988)

Have you considered returning the entire messages, or adding a parameter to decide whether to return only the last one or all of them?

**Comment by peterkeppert** [comment]
My preference is 2) and if not, then I think 1) is second best, as this way we don't venture into improving Langchain's message abstraction, which is not this toolkit's core functionality. I think it's possible we will see some improvement in the future on Langchain's side and we might be able to use it. 1) adds some complexity to ChatMessage, however I think it is a reasonable amount. Let's see if it keeps growing as more functionality comes in and if so, it might give us a reason to revisit the topic later.

**Comment by JoshuaC215** [comment]
Sounds good - let's stay with (1) for now - when I have a bit of time will take a look in some closer detail at how to simplify the existing code a bit and make it more extendable for something like BackgroundTask.

if anyone else visits this and has more feedback or input it's welcome!

**Comment by JoshuaC215** [comment]
I spent some more time thinking about this and how to make it more extendable with requirements like what's in https://github.com/JoshuaC215/agent-service-toolkit/pull/42. Here's an updated proposal:

- Add a new type `"custom"` to ChatMessage, and an optional field `custom_data: dict[str, Any]` (or similar)
- Add a utility function `send_custom_message(data: dict[str, Any])` for agents. This function would send a LangChain [message](https://python.langchain.com/api_reference/_modules/langchain_core/messages/chat.html#ChatMessage) like `ChatMessage(role="custom", content=[data])`, or maybe use the `additional_kwargs` field. This could be sent using the `adispatch_custom_event` function, similar to [the approach used here](https://github.com/peterkeppert/agent-service-toolkit/blob/0d70a2433da8fe4357063c7a6bd604160a81f9f7/src/schema/schema.py#L246-L259)
- Note: This custom type could also be returned by nodes directly in other scenarios!
- On receiving a langchain.ChatMessage with role="custom" from the agent stream, the service can convert it to a `schema.ChatMessage(type="custom", custom_data=content[0])` or similar.
- The author would be responsible for basic serialization / deserialization of their custom type e.g. calling `.model_dump() / .model_validate()` on either end if it's a Pydantic model.

I think this approach would require a minimal change to the core service / schema and be extendable to various use cases like the one @peterkeppert has been working on. I could also imagine something like an agent returning some multimedia or non-text format could make use of this (I think?)

Would love to hear any thoughts! I think I can work on making this change.

**Comment by peterkeppert** [comment]
I like this idea a lot. In my case, it removes the need for a custom Langchain message type (TaskMessage). I updated #42 along the lines of this suggestion. If we have a helper function for sending custom messages, I will update the pull request to use it.

I didn't see a need to change anything in the service. This point _"On receiving a langchain.ChatMessage with role="custom" from the agent stream, the service can convert it to a schema.ChatMessage(type="custom", custom_data=content[0]) or similar."_ can (and I think should) be handled by ChatMessage.from_langchain() function.

**Comment by JoshuaC215** [comment]
This work is completed with #72 and #74
