### ISSUE TITLE
error while attempting to bind on address ('0.0.0.0', 80): permission denied

### ISSUE THREAD

**Issue by gbaian10** [JoshuaC215/agent-service-toolkit#53]
When I run FastAPI on Ubuntu, I get this error.

![image](https://github.com/user-attachments/assets/0fe32a2b-b787-40ae-8e4b-f4fc9b02f1cc)

But the same code doesn't have this issue on Windows.

I asked the LLM and got the following answer.
**On most systems, ports below 1024 are considered privileged ports, and binding to them typically requires root or administrative privileges.**

Have you considered setting the default port to a value above 1024?

**Comment by JoshuaC215** [comment]
Two options for this:

- You can try running it directly, this works for me: `uvicorn --port 8090 --app-dir src service:app` although it doesn't automatically import the `.env`
- I'd be fine to add an environment variable used in `src/run_service.py` with default port 80 in case someone wants to change.

**Comment by gbaian10** [comment]
```py
uvicorn.run("service:app", reload=True)  # host="127.0.0.1", port=8000 for dev
```
I want to add this as a comment. Reload is very helpful for development. 
By keeping it as a comment, users can quickly switch to the desired mode.

Of course, reading the .env file to determine between these two modes is also a good approach.
For example:
```py
import uvicorn
from dotenv import load_dotenv

load_dotenv()

if __name__ == "__main__":
    import os

    if os.getenv("mode") != "dev":
        from service import app

        uvicorn.run(app, host="0.0.0.0", port=80)
    else:
        uvicorn.run("service:app", reload=True) 
```

**Comment by JoshuaC215** [comment]
Yep I’m fine with that change feel free to open a PR!
