### ISSUE TITLE
Model Name Error

### ISSUE THREAD

**Issue by gbaian10** [JoshuaC215/agent-service-toolkit#57]
The current model accepts any string as input.
If an incorrect model name is entered or a model is provided without an API key, a 500 error will occur.

![image](https://github.com/user-attachments/assets/60d91b42-b38e-4476-9c0f-f966710200ee)

It is recommended to use an Enum or dynamic Enum to check these values, allowing Pydantic to catch them and raise a 422 error
Or to define a custom error.

**Comment by JoshuaC215** [comment]
[Sounded like](https://github.com/JoshuaC215/agent-service-toolkit/discussions/64#discussioncomment-11041772) you're working on a draft PR which would address this using Enums. Looking forward to it!

**Comment by gbaian10** [comment]
Hi, would you consider raising the project's minimum Python version to 3.11?
I would like to use many practical features of 3.11, but I'm unable to do so due to the project's minimum version requirement.

For example, [StrEnum](https://docs.python.org/3/library/enum.html#enum.StrEnum) has many advantages over the regular Enum (Enum is indeed a very useful feature).
Python 3.11 also has significant performance improvements over 3.10.

Additionally, this project supports Langgraph Cloud, but [Langgraph's Docker Image](https://hub.docker.com/r/langchain/langgraph-api/tags) does not support 3.10.

This project uses uv for project management, and uv seems to have quite convenient features for switching versions.

Additionally, this project is a template, not a package, so I believe upgrading the version usually won't affect too many users (users won't import modules from this project as a third-party package).
I believe encouraging the use of newer versions of Python is also a good direction.

Another, it's a bit strange that the CI only tests against Python 3.12.
Usually, tests should be conducted for all supported versions, or at least the minimum version.
Otherwise, if I use a new syntax introduced in Python 3.12, it will pass in CI, but users with 3.10 or 3.11 will encounter issues.

**Comment by JoshuaC215** [comment]
Sure, we can update to 3.11. Good point about fixing the CI to test the minimum version.

**Comment by gbaian10** [comment]
> [Sounded like](https://github.com/JoshuaC215/agent-service-toolkit/discussions/64#discussioncomment-11041772) you're working on a draft PR which would address this using Enums. Looking forward to it!

I recently started switching computers, so there might be some delays in progress.
