### ISSUE TITLE
How to connect to Ollama

### ISSUE THREAD

**Issue by dAItime001** [JoshuaC215/agent-service-toolkit#59]
How to connect to Ollama

**Comment by JoshuaC215** [comment]
Hey @dAItime001 , I'd suggest using the LangChain <> Ollama integration described here:
https://python.langchain.com/docs/integrations/chat/ollama/

You'll want to add it similar to the existing models here:
https://github.com/JoshuaC215/agent-service-toolkit/blob/73e49ad6b0989ac831cb388ce3d8f9f71e2fe1f6/src/agent/research_assistant.py#L34-L46

Maybe also relevant:
https://github.com/ollama/ollama-python

Hope this helps!
