### ISSUE TITLE
How to integrate human in loop

### ISSUE THREAD

**Issue by Crispae** [JoshuaC215/agent-service-toolkit#80]
I am trying to run an agent with human-in-loop architecture, we apply interrupt stage, when human can provide input and then the state run on those changes. Is there any implementation like that so far in this. I will be happy to add these features, with some pointers from maintainer of this.

**Comment by JoshuaC215** [comment]
Hi @Crispae thanks!

Take a look at the discussion here and see if it makes sense:
https://github.com/JoshuaC215/agent-service-toolkit/discussions/60

If you want to work on a contribution we could keep this issue open to track that. Let me know what you think.

**Comment by JoshuaC215** [comment]
Close as stale but happy to reopen for more discussion.
