### ISSUE TITLE
Add bedrock support

### ISSUE THREAD

**Issue by madtank** [JoshuaC215/agent-service-toolkit#82]
I've forked your repo and added bedrock support using ChatBedrock. I've only used Claude 3.5, but I assume mistral and llama should work as well. 

You mentioned in your YouTube video that you are looking for a safety feature to replace llamagaurd. I'm going to attempt using AWS bedrock guardrails.

Let me know if you'd like for me to contribute.

**Comment by JoshuaC215** [comment]
Hey thanks @madtank !

Would totally welcome these contributions, probably make them separate PRs:
* Add `ChatBedrock` to `agents/models.py` with corresponding README update
* Add an example with AWS bedrock guardrails for safety

For the latter, we recently introduced the multi-agent support. Would it make sense to add this as a new agent similar to `agents/chatbot.py` which includes the safety feature? So it's nicely segmented. Sounds very cool!

**Comment by madtank** [comment]
Agreed, small iterative changes! Here's for aws bedrock support, I like the small model approach for agents, but bedrock as a lot of model options, so just thinking there could be two options platform and model id, and this would apply to the others too. https://github.com/JoshuaC215/agent-service-toolkit/pull/83

I've not started on the guardrails in bedrock, so hopefully that works out.

I'm excited to look at your multi agent support. I'm looking to build the customer support workflow where there is one assistant that can route to many different agents that are specialized.

**Comment by madtank** [comment]
@JoshuaC215 I added bedrock guardrails in my work environment and it works great. Inference is still very fast, I almost wouldn't know the check is happening. It does a good job on classifying the safety of the user input. May take me a while to get around to implementing in my personal repo, but wanted to give an update that it does work well in place of llama guard.
