### ISSUE TITLE
Use RemainingSteps instead of IsLastStep to guard against recursion limits

### ISSUE THREAD

**Issue by antonioalegria** [JoshuaC215/agent-service-toolkit#84]
I had hit some issues with IsLastStep which were recently fixed and a new managed value introduced called RemainingSteps which gives more flexibility.

See https://langchain-ai.github.io/langgraph/how-tos/return-when-recursion-limit-hits/#with-returning-state and  https://github.com/langchain-ai/langgraph/pull/2105

**Comment by JoshuaC215** [comment]
Good catch! 👍 welcome a PR or I’ll fix when I have time
